# /boot
IgnorePath /boot/\*.efi
IgnorePath /boot/\*.img
IgnorePath /boot/EFI/\*
IgnorePath /boot/loader/boot-secret-mixin
IgnorePath /boot/loader/credentials
IgnorePath /boot/loader/entries.srel
IgnorePath /boot/loader/keys
IgnorePath /boot/loader/random-seed
IgnorePath /boot/vmlinuz-\*

# /etc
IgnorePath /etc/adjtime
IgnorePath /etc/audit/\*
IgnorePath /etc/audisp
IgnorePath /etc/ca-certificates/\*
IgnorePath /etc/fonts/conf.d/\*
IgnorePath /etc/group
IgnorePath /etc/group-
IgnorePath /etc/gshadow
IgnorePath /etc/gshadow-
IgnorePath /etc/ld.so.cache
IgnorePath /etc/machine-id
IgnorePath /etc/os-release
IgnorePath /etc/pacman.d/gnupg/\*
IgnorePath /etc/pacman.d/mirrorlist
IgnorePath /etc/passwd
IgnorePath /etc/passwd-
IgnorePath /etc/shadow
IgnorePath /etc/shadow-
IgnorePath /etc/shells
IgnorePath /etc/subgid
IgnorePath /etc/subgid-
IgnorePath /etc/subuid
IgnorePath /etc/subuid-
IgnorePath /etc/ssl/certs/\*
IgnorePath /etc/.pwd.lock
IgnorePath /etc/.updated

# /usr
IgnorePath /usr/lib/\*
IgnorePath /usr/lib32/gconv/\*
IgnorePath /usr/share/applications/mimeinfo.cache
IgnorePath /usr/share/glib-2.0/\*
IgnorePath /usr/share/icons/\*/\*.cache
IgnorePath /usr/share/info/dir
IgnorePath /usr/share/mime/\*

# /var
IgnorePath /var/db/\*
IgnorePath /var/lib/dbus/machine-id
IgnorePath /var/lib/dkms/\*
IgnorePath /var/lib/debfoster/keepers
IgnorePath /var/lib/lastlog
IgnorePath /var/lib/libuuid
IgnorePath /var/lib/machines
IgnorePath /var/lib/portables
IgnorePath /var/lib/private
IgnorePath /var/lib/pacman/\*
IgnorePath /var/lib/sbctl/\*
IgnorePath /var/lib/systemd/\*
IgnorePath /var/lib/tpm2-tss/\*
IgnorePath /var/log/\*
IgnorePath /var/tmp/\*
IgnorePath /var/.updated

# Other
IgnorePath /data
IgnorePath /lost+found
